# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "calculadora.CalculadoraRequest" do
    optional :num1, :float, 1
    optional :num2, :float, 2
  end
  add_message "calculadora.CalculadoraResponse" do
    optional :resultado, :float, 1
  end
end

module Calculadora
  CalculadoraRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("calculadora.CalculadoraRequest").msgclass
  CalculadoraReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("calculadora.CalculadoraResponse").msgclass
end
